### ISSUE TITLE
Soll das Repository public sein?

### ISSUE THREAD

**Issue by Joel-dev-IMP** [lstuma/rsapython#1]
Der Link zu fleet ist für jeden öffentlich sichtbar...

**Comment by lstuma** [comment]
Der Link stollte eigentlich nach jeder fleet session ablaufen .. glaube ich. Aber so oder so müsste ich immer genehmigen wenn jemand der session joinen will

**Comment by Joel-dev-IMP** [comment]
Fair point, aber trotzdem, public? Ich weiß ja nicht...

**Comment by lstuma** [comment]
idk

**Comment by lstuma** [comment]
was spricht dafür/dagegen?
